version: '3'

services: 

  app:
    image: celsopires/desafio-nginx-node-app
    container_name: app
    command: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    tty: true
    ports: 
      - "3000:3000"
    depends_on:
      - db
  
  proxy:
    image: celsopires/desafio-nginx-node-proxy
    container_name: proxy
    restart: always
    tty: true
    ports: 
      - "8080:80"
    depends_on: 
      - app

  db:
    image: celsopires/desafio-nginx-node-bd
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql/dbdata:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root